{% set name = "versioned-hdf5" %}
# {% set version = "2.0.2" %}
{% set version = "2.0.3.dev22+gb083f80" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/i/versioned-hdf5/versioned_hdf5-{{ version }}.tar.gz
  # sha256: 7d220e4c124ac5ae6221dba5ff64aa144ac9087d3408923923825e7e7a213a02
  # git_url: https://github.com/deshaw/versioned-hdf5.git
  git_url: https://github.com/crusaderky/versioned-hdf5.git
  git_rev: f94bd80d84b61022646b9c45844379931ea6a66e

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - hdf5                                   # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - make                                   # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - python
    - python-build
    - pip
    - setuptools-scm
    - numpy
    # need to list hdf5 twice to get version pinning from conda_build_config
    - hdf5
    - zlib
    - cython
    - pkg-config
    - meson-python
    - make
  run:
    - python
    - hdf5
    - h5py >=3.8.0
    - ndindex >=1.5.1
    - numpy >=1.24.4

test:
  imports:
    - versioned_hdf5
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deshaw/versioned-hdf5
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Versioned HDF5 provides a versioned abstraction on top of h5py.

  description: |
    Versioned HDF5 provides a versioned abstraction on top of `h5py`.
    This was created by the D. E. Shaw group <https://www.deshaw.com/> in conjunction
    with Quansight <https://www.quansight.com/>.
  doc_url: https://deshaw.github.io/versioned-hdf5
  dev_url: https://github.com/deshaw/versioned-hdf5

extra:
  recipe-maintainers:
    - peytondmurray
    - crusaderky
    - melissawm
    - asmeurer
    - scopatz
