{% set name = "versioned-hdf5" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deshaw/versioned-hdf5/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: d47f3efe73bc9f2d79ea69af1eea2f3ee033f90436afd13be38341404cf76474

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py
    - ndindex >=1.3

test:
  imports:
    - versioned_hdf5
    - versioned_hdf5.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deshaw/versioned-hdf5
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Versioned HDF5 provides a versioned abstraction on top of h5py.

  description: |
    Versioned HDF5 provides a versioned abstraction on top of `h5py`.
    This was created by the D. E. Shaw group <https://www.deshaw.com/> in conjunction
    with Quansight <https://www.quansight.com/>.
  doc_url: https://deshaw.github.io/versioned-hdf5
  dev_url: https://github.com/deshaw/versioned-hdf5

extra:
  recipe-maintainers:
    - melissawm
    - asmeurer
    - scopatz
